---
title: "seqwrap-paper"
format: gfm
---

## Introduction

This repository contains details of the relevant files, data and code needed to reproduce the results and figures presented in the [seqwrap](https://github.com/trainome/seqwrap) paper.

## Relevant files and folders

-   `supplement.qmd` Running this file reproduces the supplementary documents including the tables and figures therein

-   `/R` This directory contains the scripts used to produce the results present in the paper. Below are short descriptions of what each file does

     i. `data-prep.R` . If the libraries in this file are installed, running this script will download the raw gene counts from the [Pillion study](https://pubmed.ncbi.nlm.nih.gov/36070371/) , use seqwrap to build and save a preliminary model .

     ii. `simulation-functions.R` Contains R functions used at different points of the analysis such as the function to simulate data sets and summary functions. The other files (except data-prep.R) loads and executes this file to make the functions and variables in the script available in the R environment

    iii\. `m1-m5-pillion-data.R` This file builds ands save the models based on real world data from the [Pillion study](https://pubmed.ncbi.nlm.nih.gov/36070371/)

    iv\. `make-sims.R` Runs the files `simulations.R` and `simulations2.R` which contain the generation and modelling of the simulated data set reported in the paper

-   `/figures` The R files in this directory reproduces the figures in the paper

    `figure-1.R` reproduces Figure 1

    `figure-2.R` reproduces Figure 2

    `figure-3.R` reproduces Figure 3

    `figure-opts.R` defines the custom color palette used in the figures.

## Reproducing the analysis in the paper

To reproduce the analysis from scratch, we recommend you run the scripts in this order

1.  `/R/m1-m5-pillion-data.R` Would reproduce the case study analysis

2.  `/R/make-sims.R` Would reproduce the simulation data and analysis

3.  `supplement.qmd` Would reproduce the supplementary file

4.   `/figures/figure-1.R` Would reproduce Figure 1

5.   `/figures/figure-2.R` Would reproduce Figure 2

6.  `/figures/figure-3.R` Would reproduce Figure 3
