---
title: "Response to comments: seqwrap: an R package for flexible iterative fitting of high-dimensional data"
author:
  - name: Chidimma Echebiri
    email: chidimma.echebiri@inn.no
    affiliation:
      - name: University of Inland Norway
        department: Department of Biotechnology, PhD programme in applied ecology and biotechnology
  - name: Rafi Ahmad
    email: rafi.ahmad@inn.no
    affiliation: 
      - name: University of Inland Norway
        department: Department of Biotechnology
      - name: UiT - The Arctic University of Norway, Tromsø, Norway
        department: Institute of Clinical Medicine, Faculty of Health Sciences
  - name: Stian Ellefsen
    email: stian.ellefsen@inn.no
    affiliation: 
      - name: University of Inland Norway
        department: Department of Public Health and Sport Sciences 
  - name: Daniel Hammarström*
    email: daniel.hammarstrom@inn.no
    affiliation: 
      - name: University of Inland Norway
        department: Department of Public Health and Sport Sciences 
    attributes:
      corresponding: true
format: typst
bibliography: resources/bibliography.bib
csl: resources/bmc-bioinformatics.csl
---

`#v(5em)`{=typst}

### Editor's comments and authors' responses
`#strong([Authors response.])`{=typst} 

Dear Editor,
We thank you for your detailed feedback and the opportunity to further revise our manuscript. We appreciate the time and effort invested in evaluating our manuscript. We also appreciate BMC Bioinformatics' commitment to reproducible research and have therefore made efforts to address these aspects of our work. See responses to specific comments below.  

*Before the manuscript can be considered further, please revise the manuscript and provide the following:*

1. *Complete R code/scripts used to generate all analyses, figures, and tables reported in the manuscript.*

`#strong([Authors response.])`{=typst} Complete R codes and scripts used to generate the results presented in the manuscript have been published in the GitHub repository https://github.com/trainome/seqwrap-paper with a detailed README file containing instructions for reproducing results in the paper. Additionally, if permitted, we will provide a zipped version of the code repository as supplementary material to this manuscript.

2. *All datasets required to reproduce the results, or clear instructions for accessing them if they are publicly available*

`#strong([Authors response.])`{=typst}The case study data used in the manuscript and the supplementary document are openly available; Pillon et al ., [@pillon2022], GSE202295; and  Dungan et al. [@dungan2022], GSE195707, respectively. The simulation data sets can be generated using the code specified in the manuscript GitHub repository (https://www.github.com/seqwrap-paper), which is also available as supplementary material. The simulated data, together with the model estimates needed to directly reproduce results in the manuscript, can also be downloaded from DataverseNO (https://doi.org/doi:10.18710/I7U71O) to avoid a computationally intensive estimation process. We have highlighted this option in the code repository. 

3. *The code should be provided in an executable and well-documented form, allowing readers to reproduce the results step by step.*

`#strong([Authors response.])`{=typst} The code repository is documented to enable reproduction of the results in the manuscript. The README section of the repository (supplementary material and https://github.com/trainome/seqwrap-paper) provides step-by-step instructions for reproducing the results.

4. *If the datasets and scripts are already included within the R package or repository, please ensure that this is clearly indicated in the manuscript and provide direct links and instructions for reproducing the results.*

`#strong([Authors response.])`{=typst} We have updated the **Availability of data and materials** section of the manuscript which now reads 
 
> All data presented in the paper (and supplementary material) are openly available (Pillon et al ., [@pillon2022], GSE202295; Dungan et al. [@dungan2022], GSE195707). The code for the simulation study is available at https://github.com/trainome/seqwrap-paper. Simulation results can be replicated using code provided in the repository https://github.com/trainome/seqwrap-paper, simulated data sets and results can also be downloaded from DataverseNO: Chidimma Echebiri, Stian Ellefsen, Rafi Ahmad, and Daniel Hammarstr&ouml;m. 2026. "Simulated Data Sets for: Seqwrap: An R Package for Flexible Iterative Fitting of High-Dimensional Data. https://doi.org/10.18710/I7U71O"

### Note to Editor

In the first review round, Reviewer 1 recommended we expand our literature review and include three specific references (Chen and Qiu 2023, DOI: 10.32614/RJ‑2023‑080; Chen 2022, DOI: 10.1371/journal.pone.0276664; and Chen and Tsao 2024, DOI: 10.1093/bioinformatics/btae731). We found all three references relevant to the broader methodological landscape.  

However, because our manuscript focuses specifically on R‑based packages, we decided to only include the two references that introduce R‑based tools. The remaining reference (Chen 2022, DOI: 10.1371/journal.pone.0276664) describes a Python‑based workflow. For conceptual and technical consistency in the manuscript and to avoid mixing software ecosystems that might distract from the paper's scope, we chose not to incorporate that reference. 

In the current review round, Reviewer 1 again encouraged us to add the previously excluded reference. After discussion among the authors and a consideration of the manuscript's scope, we believe that including a Python‑based tool in a paper focused on R packages would introduce unnecessary conceptual heterogeneity. For this reason, we respectfully maintain our earlier decision not to add this reference.

We hope this explanation clarifies our rationale, and we remain open to further guidance should the editorial team deem it essential to include the reference in our paper. 


### Reviewer comments and authors' responses

`#strong([Authors response.])`{=typst} We thank the reviewers for once again reviewing our manuscript and making comments and recommendations all aimed at upholding the standard expectation for methodological papers and software packages. We are addressing the reviewers' comments below.

#### Reviewer 1

*I appreciate the authors' great effort in preparing this revision. The authors have adequately addressed most of the previous comments. However, I have two additional very minor comments and recommend minor revision:*

1.   *I just noticed that a suggested reference (Chen 2022, DOI: 10.1371/journal.pone.0276664) appears to be missing from the revised manuscript. I would suggest adding this reference, as it also developed an R package for high-dimensional data, particularly for classification problems.*

`#strong([Authors response.])`{=typst} We thank the reviewer for the suggestion. We agree that the suggested reference (Chen 2022, DOI: 10.1371/journal.pone.0276664) is relevant in the context of high-dimensional data analysis tools. However, we note that the reference is a Python-based tool, whereas our manuscript focuses on R-based methods intended for R-based analysis. To maintain conceptual and technical consistency, we included only the R-based packages recommended by the reviewer which helped not just position our package but made the review more comprehensive. We have added a note to highlight (in the introduction) that the general discussion concerns examples from the R ecosystem.

2. *Since the manuscript title contains the term "high-dimensional," users or readers may naturally expect some form of variable selection. This is why I raised this comment previously.
    According to your response, you mentioned that "each target gets its own set of estimates, and selection between targets as features has to be done by the user after model fitting." Does this imply that informative genes should be pre-determined by the users? I would suggest that the authors clarify this point in the manuscript.*

`#strong([Authors response.])`{=typst} We thank the reviewer for pointing out the potential for misunderstanding regarding variable selection. To clarify, our package is not designed to perform formal variable selection across predictors. Instead, the package fits a separate model for each target (e.g., gene or protein), and the resulting estimates are returned to the user. This does not require users to pre‑select informative targets; rather, targets can be evaluated and filtered after model fitting based on their estimated effects. This is the approach of similar packages, such as Deseq2, limma, or EdgeR, where target expression levels (in the context of gene expression analysis, e.g., genes or transcripts) are modelled target-by-target, and estimates are used for downstream analyses. Downstream analyses may rank or select targets based on estimates (log-fold changes, p-values or other metrics) for, e.g., gene-set analyses. We believe that this approach is described in the introduction and implementation. To make it clearer in the implementation section, we have added the following sentence:

> This approach enables the user to obtain target-specific estimates from a specified statistical model for downstream analyses, such as differential expression or gene set enrichment analyses. 


#### Reviewer 2

*Many thanks for considering my previous comments. However, I believe that in order to have a fully reproducible paper, an associated file with the R code to run all the necessary analyses and plots in paper is needed. The authors have provided a supplementary.pdf file with lots of R code chunks. However, this is not suitable for reproducibility as it involves copying and pasting tens of R code chunks.*

*Hence, please provide a single file with R code so that we can reproduce all the examples in the paper. If simulations are used, please use set.seed() before sampling the simulated data. Furthermore, make sure that you comment the R code appropriately so that the different results and plots in the paper can be identified in the code*

`#strong([Authors response.])`{=typst} We thank the reviewer for this suggestion regarding reproducibility. However, it is not manageable to keep all R code in a single file. The code used to generate results in the manuscript, figures, and tables is available in a GitHub repository. We have highlighted this in the updated version of the manuscript and added a zipped version as supplementary material. The repository is available at https://github.com/trainome/seqwrap-paper. 
In the repository, we have updated the README file to clarify which files need to be run to reproduce the results. The manuscript and supplementary file are both qmd-files, which enable the execution of R code. That said, we have extracted the R code from the supplement file to make it sourcable and added it to the repository.

We have used simulated data in our analyses; however, simulations and modelling of the generated data are computationally costly. We have therefore uploaded the generated datasets to DataverseNO (https://doi.org/10.18710/I7U71O) and provided instructions for using them, along with the repository. For all simulations, a specific seed is used to enable reproducibility.

We believe these additions fully address the reviewer's helpful suggestions and significantly enhance the reproducibility and transparency of the work.
